### ISSUE TITLE
Что за 36 и 25? Комментарии по ним нужны. Хотелось бы.

### ISSUE THREAD

**Issue by MentorTutor** [RedBrean/Project-deltaV#3]
https://github.com/RedBrean/Project-deltaV/blob/98bfb11e14f75a5ea855e066edda4693992130e0/deltaV_main.py#L31-L32

**Comment by VladDryazgov** [comment]
Здравствуйте, это размещение текста на экране в долях от высоты экрана, у этих чисел нет очень глубокого смысла.

**Comment by VladDryazgov** [comment]
Сделано, кстати

**Comment by MentorTutor** [comment]
Хорошо, спасибо )
