### ISSUE TITLE
Что числа означают? Хотел бы увидеть побольше комментариев.

### ISSUE THREAD

**Issue by MentorTutor** [RedBrean/Project-deltaV#4]
https://github.com/RedBrean/Project-deltaV/blob/98bfb11e14f75a5ea855e066edda4693992130e0/deltaV_main.py#L39

**Comment by VladDryazgov** [comment]
Это предустановленные настройки времени, ладно сделаю комментарий.

**Comment by VladDryazgov** [comment]
А, уже было сделано

**Comment by MentorTutor** [comment]
Ок )
