### ISSUE TITLE
Можно ли это как-то оптимизировать?

### ISSUE THREAD

**Issue by MentorTutor** [RedBrean/Project-deltaV#5]
https://github.com/RedBrean/Project-deltaV/blob/98bfb11e14f75a5ea855e066edda4693992130e0/deltaV_main.py#L131-L146

**Comment by RedBrean** [comment]
Нельзя. Это просто бинд кнопок

**Comment by VladDryazgov** [comment]
Сдалано

**Comment by VladDryazgov** [comment]
Сделано

**Comment by MentorTutor** [comment]
Круто, спасибо :)
